services:
  - docker

install:
  - echo "POSTGRES_USER=admin" >> .env
  - echo "POSTGRES_PASSWORD=Password1" >> .env
  - echo "DATABASE_URL=postgres://admin:Password1@postgres/mordhub" >> .env
  - echo "STEAM_API_KEY=$STEAMAPIKEY" >> .env
  - echo "COOKIE_SECRET=RMCLVcuHYboeeOgDxm53aLkNPKC4UMWU" >> .env
  - echo "SITE_URL=http://localhost:3000" >> .env

script:
  - docker-compose up
  - ./biosoftware | while read line; do echo "$line" | grep -q "Starting server on" && killall docker-compose; done

# TODO: Push to docker hub?
# TODO: Run tests
