language: minimal

services:
  - docker

install:
  - curl -LO https://github.com/BurntSushi/ripgrep/releases/download/11.0.1/ripgrep_11.0.1_amd64.deb
  - sudo dpkg -i ripgrep_11.0.1_amd64.deb
  - echo "POSTGRES_USER=admin" >> .env
  - echo "POSTGRES_PASSWORD=Password1" >> .env
  - echo "DATABASE_URL=postgres://admin:Password1@postgres/mordhub?sslmode=disable" >> .env
  - echo "STEAM_API_KEY=$STEAMAPIKEY" >> .env
  - echo "COOKIE_SECRET=RMCLVcuHYboeeOgDxm53aLkNPKC4UMWU" >> .env
  - echo "SITE_URL=http://localhost:3000" >> .env

script:
  - docker-compose up --abort-on-container-exit | while read line || exit 0; do echo "$line" | rg --passthru "Starting server on" && killall docker-compose; done

# TODO: Push to docker hub?
# TODO: Run tests
