version: '3'
services:
  mordhub-backend:
    build: .
    env_file: .env
    environment:
      - WAIT_HOSTS=postgres:5432
    networks:
      - backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: "postgres:alpine"
    environment:
      - POSTGRES_DB=mordhub
    env_file: .env
    networks:
      - backend
    ports:
      - "7654:5432"

  # Note that this almost certainly will not work on Windows.
  # Simply comment this out and it should work fine nonetheless.
  netdata:
    image: netdata/netdata
    hostname: mordhub.com
    ports:
      - 19999:19999
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

networks:
  backend:
