CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  steam_id BIGINT UNIQUE NOT NULL
);

CREATE TABLE loadouts (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  name VARCHAR(80) NOT NULL,
  data VARCHAR NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE images (
  id SERIAL PRIMARY KEY,
  url VARCHAR(100) NOT NULL,
  loadout_id INTEGER NOT NULL REFERENCES loadouts(id),
  position INTEGER NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE likes (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  loadout_id INTEGER NOT NULL REFERENCES loadouts(id)
);
